# Generated by Django 2.2 on 2019-06-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysandwich', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='img',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='img_big',
            field=models.FileField(blank=True, upload_to='ingredients/big'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='img_small',
            field=models.FileField(blank=True, upload_to='ingredients/small'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
