# Generated by Django 2.2 on 2019-06-14 17:52

from django.db import migrations, models
import mysandwich.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysandwich', '0002_auto_20190614_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='img_big',
            field=models.FileField(blank=True, upload_to='static/images/ingredients/big'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='img_small',
            field=models.FileField(blank=True, upload_to=mysandwich.models.small_directory_path),
        ),
    ]
