# Generated by Django 2.2 on 2019-06-14 17:58

from django.db import migrations, models
import mysandwich.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysandwich', '0003_auto_20190614_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='img_big',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='img_large',
            field=models.FileField(blank=True, upload_to=mysandwich.models.large_directory_path, verbose_name='Large image'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='img_small',
            field=models.FileField(blank=True, upload_to=mysandwich.models.small_directory_path, verbose_name='Small image'),
        ),
    ]
