# Generated by Django 2.2 on 2019-06-20 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysandwich', '0004_auto_20190614_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 21, 44, 28, 38615)),
        ),
    ]
