# Generated by Django 2.2 on 2019-06-20 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysandwich', '0005_auto_20190620_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 21, 46, 20, 76638, tzinfo=utc)),
        ),
    ]
