# Generated by Django 2.2 on 2019-06-20 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysandwich', '0006_auto_20190620_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 22, 16, 44, 633866, tzinfo=utc)),
        ),
    ]
