# Generated by Django 2.2 on 2019-06-20 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysandwich', '0007_auto_20190620_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
