# Generated by Django 2.2 on 2019-06-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysandwich', '0009_remove_ingredient_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
