# Generated by Django 2.2 on 2019-06-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysandwich', '0010_ingredient_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3),
        ),
    ]
